site_name: "t3rrific.com &#124; TYPO3 on AWS"
site_url: https://t3rrific.com/
docs_dir: src/
site_dir: docs/
plugins: []

theme:
    name: null
    custom_dir: theme/
    highlightjs: false

markdown_extensions:
    - attr_list

extra_css:
    #- https://www.typo3-on-aws.org/assets/css/website.css
    #- https://cdnjs.cloudflare.com/ajax/libs/prism/1.16.0/themes/prism.min.css
    - /_assets/css/t3rrific.css
    #- css/t3rrific.css
    - css/theme.css
    - css/prism.css

extra_javascript:
    #- https://cdnjs.cloudflare.com/ajax/libs/prism/1.16.0/components/prism-core.min.js
    #- https://cdnjs.cloudflare.com/ajax/libs/prism/1.16.0/plugins/autoloader/prism-autoloader.min.js
    - js/theme.js
    - js/prism.js

extra:
    version: 1234
